#!/usr/bin/env bash

# Install fish (No need to run, since fish is included in brewfile
# brew install fish

FISH_PATH=(brew --prefix fish)

# Register Fish as an official shell
$FISH_PATH | sudo tee -a /etc/shells

# Set it as default shell
chsh -s $FISH_PATH
